[package]
name = "sociarium-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sociarium-adapter = { path = "../sociarium-adapter" }
sociarium-core = { path = "../sociarium-core" }
thiserror.workspace = true
